# Generated by Django 3.2.8 on 2022-05-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
